### ISSUE TITLE
Roles assignment - dev and production

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#102]
ISSUE 1: When a user creates a new organization, we must automatically assign the GROUP role of organization admin. That is not currently happening on production.

ISSUE 2: When user is granted membership to an existing group, we must auto-assign, at minimum, DRUPAL role of editor. When org admin approves member, they are given a chance to assign group membership.

ISSUE 3: **\* Emails from systems sometimes seem to be sent on a delay. This has been true for dev and production. When I sign up, I expect to see an email in my inbox fairly soon. Can we lessen that delay? Seems excessively long. It varies from day to day.

**Comment by kngfrank** [comment]
I may need to test this again Monday when I'm not braindead.

**Comment by kngfrank** [comment]
UPDATE: On the production site, many users are not assigned their appropriate group roles once they've been accepted into a group. We need this to be an automated process.

Also need to be sure that when a user creates a new organization, they are assigned the correct group role.

**Comment by kngfrank** [comment]
I attempted to write a rule granting group permission to the user creating a new organization, but it's not working. It's called "Assign org admin group role."

**Comment by emasters** [comment]
This should be 3 issues not 1.
ISSUE1 is fixed.
ISSUE 2 is now #125
ISSUE 3 is now #126
