### ISSUE TITLE
inquiry  via jreiskin@ccdconline.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#105]
From: jreiskin@ccdconline.org<br>
Subject: inquiry<br>
Date: May 04, 2016 at 02:32PM<br><br>
How does one become an eligible organization to develop classes on this website? Sincerely,&nbsp; Julie Reiskin,&nbsp; Executive DirectorColorado Cross-Disability Coalition1385 S. Colorado Blvd. Suite 610-A &nbsp; Denver, CO 80222Direct Line 720-961-4261Direct Private Fax 303-567-6582Organizational Line 303-839-1775 Organizational Fax&nbsp;303-648-6262 Legal Program's Fax&nbsp;720-420-1390 http://ift.tt/1OewmOr a Member of CCDC for FreeLike us on FacebookFollow us on Twitter Our future is best planned today &hellip; we must demand real and meaningful disability community engagement.&nbsp; Nothing about us without us, ever! &nbsp; &nbsp;&nbsp;CCDC is a member of http://ift.tt/24rvcfd NOTHING ABOUT US WITHOUT US -- EVER The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review,&nbsp;re-transmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.<br><br>
via Gmail

**Comment by KathyDaniels** [comment]
I responded to her.  ksd
