### ISSUE TITLE
how do org admins add new members??

### ISSUE THREAD

**Issue by KathyDaniels** [CCALI/learnthelaw#130]
We need instructions for Org Admin on how to add a new site user.  At this point they get an email that says: " ________ requests membership for group '___________________' in https://www.learnthelaw.org/statewide-legal-services-connecticut."

And there is no indication of what to do.  I wanted to test to see if the Group membership was added and couldn’t see how to add the new member.

**Comment by emasters** [comment]
@KathyDaniels I thought you had created instructions for that last winter?

**Comment by KathyDaniels** [comment]
I’ll explain when we talk

**Comment by emasters** [comment]
Need to find where email is being sent from and change message so that it sends org admin toa more useful site.

**Comment by emasters** [comment]
The email is sent from a rule action at `http://dev.learnthelaw.org/admin/config/workflow/rules/reaction/manage/og_og_member_subscribe_pending_org_admin/edit/7`
I've updated the text of the message as follows

``` [group:author:name],

[account:name] requests membership for group '[group:title]'. To approve or deny this request please visit [site:url]group/node/[group:nid]/admin/people and edit the request.

[account:name] added the following note to the membership request form:
[og_membership:og-membership-request]
```

This results in a message that looks like 

``` etest10,

etest11 requests membership for group 'CALI Test'. To approve or deny this
request please visit http://dev.learnthelaw.org/group/node/236/admin/people
and edit the request.

etest11 added the following note to the membership request form:
Take 3.
This is interesting.
```

**Comment by emasters** [comment]
I updated rule on production.
