### ISSUE TITLE
link to add classrooms if no classrooms exist not working

### ISSUE THREAD

**Issue by KathyDaniels** [CCALI/learnthelaw#137]
Kate had earlier reported, but I didn't see it here:

Hi Elmer,

Regarding the issue with the link to add classrooms if no classrooms exist: The code I originally wrote is present in the “No results behavior” of the view, so I don’t know why it stopped working. I can’t do any more about this and I’m out of time. I hope you can fix it!

Thanks,
Kate

**Comment by kngfrank** [comment]
I fixed this one.
