### ISSUE TITLE
Menu items removed for regular users

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#28]
The structure and config menu items are available to regular users. I'm not sure they'll know what to do with this:

Would probably eliminate structure and config items from menu altogether.

Can we create a new help button that doesn't go to generic drupal help, but goes to the instructions Kathy wrote?

**Comment by emasters** [comment]
I'm going to remove that navbar altogether and craft another menu for content creators.

**Comment by emasters** [comment]
Added a creator menu with links for Classrooms, Organizations, and help. Placed menu block in user bar first region.
Menu needs to be styled to fit in line. Assigning to @kngfrank for the styling.

**Comment by kngfrank** [comment]
All set.
