### ISSUE TITLE
Nothing in Groups Audience dropdown

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#31]
See this link for example:
http://dev.learnthelaw.org/node/121/edit

**Comment by emasters** [comment]
This is caused by the Organization not being designated as "Group" when it is created. I need to set things up so that all Orgs are set as Groups by default and cannot be changed.

**Comment by emasters** [comment]
Seems that only groups a user creates are showing in that list. This is not the way it's supposed to work. Should show any groups a user belongs to. 

Need to check permissions as well as how group membership really works.

**Comment by emasters** [comment]
Working through OG settings. 
- Turned on user view and edit in OG context. That added list of orgs to user page.
- OG Permissions were not set. Made some adjustments to let group members attach classroom entries to groups. Makes the group audience selector visible to all members of a group.

Working on dev, needs to be pushed to code.
