### ISSUE TITLE
Relations under Add New Classroom

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#34]
Do we want users being able to choose "Relations" on the "Add new classroom" page?

![relations](https://cloud.githubusercontent.com/assets/4311947/11001622/161cf4ba-8476-11e5-81d0-ec2c30a8e3c1.JPG)

**Comment by emasters** [comment]
We do not want them to do that. Looking into it.

**Comment by emasters** [comment]
This is normal behavior for Drupal. Making it disappear is going to require some coding. Will circle back to it. 

We should test to see what happens if someone  sets there Classroom as a child of another one.

**Comment by kngfrank** [comment]
I hid this via CSS.
