### ISSUE TITLE
Classroom entries page

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#35]
http://dev.learnthelaw.org/admin/classrooms/entries

On this page I think we should only see our own entries. I can't actually do anything with the other orgs' entries on this page. A delete button is available, but I'm not actually able to delete entries that belong to other orgs. This list is going to become unwieldy fast if we are seeing everyone's entries.

I think this page should exist to manage my own classroom entries. I have no need to see others' classrooms, or even their entries, on this page. 

You could make an argument that this is a good place to clone entries belonging to other orgs. But if I wanted to clone an entry, this wouldn't be the place I would want to do it. I would want to visit the actual page that I want to clone, and clone it from there. That way I would know exactly what I am cloning. Thoughts?

**Comment by emasters** [comment]
I added a relationship and filter to the view for Classroom Entries so now you only see your own entries. 
I need to figure out how to limit the list of Classrooms in the exposed filter the same way. Cloning needs to be its own separate thing.

**Comment by kngfrank** [comment]
This is closed. Opening a separate issue for the other issue mentioned in Elmer's comment.
