### ISSUE TITLE
Jessica Bolack Frank - issues reported in testing  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#37]
From: KDaniels@ghla.org<br>
Subject: Jessica Bolack Frank - issues reported in testing<br>
Date: November 09, 2015 at 12:43PM<br><br>
She did send screenshots in case any questions.&nbsp; They are posted on Slack 10/15/15. 
Rich text editor has weird spacing with toolbar 
Jurisdiction for classroom no &ldquo;all&rdquo; option where do I fit then? 
No explanation of what the classroom is once they click into it. Just straight into the first step? 
So then every classroom should have a welcome screen as the first step that explains what the person will learn. 
Why does calculator show up in my classroom? 
&ldquo;Bold and indent&rdquo; doesn&rsquo;t actually indent the step in the classroom display. They do indent when you select just &ldquo;indent&rdquo; and not &ldquo;bold and indent&rdquo; 
Bullets get cut off in the classroom display. It doesn&rsquo;t matter how big I made the screen.
 It is a little difficult to create long text in the classroom entry text editor. I am hitting this issue when editing the classroom entry called &ldquo;Automating the Template Creating Fields and Adding Variables&rdquo; in my Sample Exercise classroom. &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
> There is an "all" under jurisdiction.
> Someone can tell her that the first step could be a welcome screen.
> If lots of people question the calculator, maybe we can remove it. I dunno.
> Will fix bullets and indents. Github issues have been created for this.
> I don't know what to say about the editor... It's not something we can fix.

Closing.
