### ISSUE TITLE
Lisa Stansky - issues reported in testing  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#39]
From: KDaniels@ghla.org<br>
Subject: Lisa Stansky - issues reported in testing<br>
Date: November 09, 2015 at 12:50PM<br><br>
Hi Kathy, I&rsquo;ve been working with the online classrooms, and I&rsquo;ve been able to create a classroom frame with three steps. I had to experiment a bit to add steps to the classroom, but once I figured that out it made sense (the link opened in IE, which may be not the best choice for me). 
I was worried that publishing the classroom entry would put it on your site for all to see, but then I saw that I needed to assign the entry to my test SLLS site. 
The only concern I had is that I (or someone else) could inadvertently add a step to another classroom. Is that possible? 
The only thing that seemed like a bug but turned out not to be a bug was the process for uploading an image file. For me that was a two-step process &ndash; to click the image icon in edit mode then to check for the green &ldquo;Upload&rdquo; arrow on the left to add an image from my own files. Here&rsquo;s a screenshot below to show you what I saw. Hope this is helpful, and I&rsquo;ll keep working with the site to see what else turns up. &ndash; 
Lisa 
Hi Kathy, The links embedded in the instructions opened in IE. I use Firefox for my SWWS editing, and I often use IE for other purposes. Just wanted to let you know in case you had a specific browser in mind that people should use.&nbsp; When I get a chance I will send screenshots of the steps I used to add steps to my classroom &ndash; there are two displays that initially threw me off, but I figured it out. Hope this is helpful. &ndash; Lisa &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
> Someone could inadvertently add a step to multiple classrooms. As with anything else they do regarding web publishing, they have to be careful.
> 
> The image upload process is two steps and doesn't seem to be broken.
> 
> We can't control what browser opens. That's on the user's end.

Doesn't seem to be anything in here that needs fixing, so closing.
