### ISSUE TITLE
Whit Freer - issues reported in testing  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#40]
From: KDaniels@ghla.org<br>
Subject: Whit Freer - issues reported in testing<br>
Date: November 09, 2015 at 12:52PM<br><br>
Overall it was pretty darn easy and straightforward, very very nice!!! &nbsp;
The one thing I couldn&rsquo;t figure out was how to add someone else&rsquo;s steps into my classroom.&nbsp; So, say you wrote 3 steps that I wanted in mine I couldn&rsquo;t get them into my classroom.&nbsp; 
Maybe in a future revision might be cool to be able to search within the &lsquo;classroom entries&rsquo; to try and find something.&nbsp; 
The click and filter is slightly not apparent, took me a few times to see that that&rsquo;s what it does, but was easy enough to figure out. &nbsp; &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
When we start the cloning and sharing process, we'll just need to make it easy for people to figure out.

Closing.
