### ISSUE TITLE
need form for Editor to sign up for organization

### ISSUE THREAD

**Issue by KathyDaniels** [CCALI/learnthelaw#54]
ideally they would select their organization from the list of registers orgs.  if the org is not in the list we ask them if they would be the org admin and take them to that sign in form.
once they have signed up we would be notified for now since there are few orgs - down the road the registered org admin would be notified.

**Comment by emasters** [comment]
I think that this needs to be put in the hands of the org admins from the very beginning. Org admins need to know that part of their responsibility in signing on to this is to manage users for their organization.

**Comment by kngfrank** [comment]
Working on this now. Closing issue.
