### ISSUE TITLE
Members tab showing on org pages

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#56]
Check out any organization page while you're logged out. The membership field shows up but I'm not sure why: https://www.learnthelaw.org/ctlawhelp

**Comment by emasters** [comment]
Probably because anonymous has permission to see member lists. Should be restricted to logged in users.

**Comment by kngfrank** [comment]
I can't find the permissions to hide the member tab. 

Also need to note that 

Permissions and Roles are read only, but show up for organization admins. Could be confusing and may want to remove.

**Comment by kngfrank** [comment]
Can we take care of this? Hide via CSS, at least? I am not set up to work on the site currently.

**Comment by emasters** [comment]
Found fix at http://drupal.stackexchange.com/a/103264. Member tab now only shows for org admins.
