### ISSUE TITLE
Views - Filtering out fields

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#64]
> We need to filter out classrooms that are “unlisted” and “inactive.” 
> The filter settings in the view on this page
> (https://www.learnthelaw.org/classrooms) are correct. When I try to 
> apply them to an organization listing page, they aren’t available for 
> me to filter on. That makes me think it’s a relationship setting. But 
> I don’t know much about views relationships.

**Comment by emasters** [comment]
related to #61

**Comment by kngfrank** [comment]
Fixed.
