### ISSUE TITLE
Error on groups members page

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#68]
https://www.learnthelaw.org/node/61/members

Role: Organization admin

Error message
Notice: Undefined index: quantity in omega_views_mini_pager() (line 214 of /vol/data/ocm/sites/all/themes/omega/omega/includes/omega.theme.inc).

I found this drupal thread:
https://www.drupal.org/node/1828552

Don't know how to fix.

**Comment by emasters** [comment]
Since this doesn't effect performance I just suppressed the error so no one sees it.
