### ISSUE TITLE
Add OG field reference to Classroom Taxonomy

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#83]
Adding a reference back to t he Organization from the Classroom taxonomy term ties the term to the org helping improve context. It provides better filtering and relationship options in Views.
Implementation requires adding this value to each existing Classroom term. This needs to be done by a site admin as a one time thing. Once deployed it will be an integral part of Classroom creation.

**Comment by KathyDaniels** [comment]
TESTED: as org admin when I create a new class, I see "Groups Audience" where I can select the organization.   As Site Admin I can browse to the classrooms list thru Structure/Taxonomy and edit other orgs classrooms.  I do see the "Groups Audience" field there to associate the classroom with an org.

**Comment by emasters** [comment]
@KathyDaniels Each existing Classroom needs to associated with the appropriate organization and this will need to be done on production when the new version is rolled out. From launch forward this will be done automatically when each Classroom is created.
