### ISSUE TITLE
Add Classroom Admin panel page and tab to Org context

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#84]
This panel adds the Classroom Admin view to a tabbed page in the org context. It provides important org context for administering Classrooms.

**Comment by emasters** [comment]
Org admins and editors should be able to see all of the Classrooms available to the organization, but current state is that they can only edit Classrooms they created. This needs to be fixed.

**Comment by KathyDaniels** [comment]
TESTED:  both org admin and org editor can see classroom admin panel page and tab.  
Org Admin can edit own classrooms.  Org Editor cannot edit org admin classes.
Org Editor can't create classes so can't test the other way around.

**Comment by emasters** [comment]
As of 7/21/16 non-member logged in users can see the tab and the listing. This needs to be changed so the tab only shows to admins and editors of the group.
