### ISSUE TITLE
Set homepage to Org homepage for logged in org admins and editors

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#87]
Navigation needs to be reworked for these users so that they remain in the organization context as they move through the site.

**Comment by KathyDaniels** [comment]
TESTED:  when I log in as an org admin, it does go to the org homepage.  once I leave that org homepage, there is no way to get back to it.  I do see the site classrooms and entries when on the org homepage.  maybe a button to get back to the org homepage.

**Comment by emasters** [comment]
login works on dev. Opening new issue for navigation issue.
