### ISSUE TITLE
Set Org context in Classroom URLs

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#88]
To complete the contextualization of the site the URLs for individual Online Classrooms need to be altered to include a reference to the organization in the OC URL. Form should be `http://dev.learnthelaw.org/%org_ref/classroom/2179` where `%org_ref` is a string that identifies the organization.

**Comment by KathyDaniels** [comment]
TESTED:  what I am seeing for classrooms I created is http://dev.learnthelaw.org/classroom/****  where the 4-asterisks are a 4-number string for the classroom.  The %org_ref is not showing up.  I am logged in as org admin.

**Comment by emasters** [comment]
@KathyDaniels That URL string hasn't been implemented yet, that is why you aren't seeing it.

**Comment by emasters** [comment]
URL format is /group/##/classroom/#### where ## is the organization id and #### is the classroom id. This will be helpful in analytics.
