### ISSUE TITLE
New Org - can it be 1 step instead of 2???  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#91]
From: KDaniels@ghla.org<br>
Subject: New Org - can it be 1 step instead of 2???<br>
Date: March 14, 2016 at 01:58PM<br><br>
After a new Org Admin clicks on the link to &ldquo;registering your organization&rdquo; and fills out the form, the organization is NOT created even though the form is filled out and submitted. &nbsp; If I log in as the Org Admin and then do &ldquo;Add Organization&rdquo; the Org is created and the Org Admin goes to the correct Org Homepage when logging in.&nbsp; It feels like the Registering Org and Add Org should be combined, is that possible? &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
I would not recommend it all happening in one automated step. That would open the site up to spam.

Maybe we need to call the first step "Applying." 

In the first step, the information is submitted to us and we verify that the applicant is legit.  Then we assign org admin permission to the user who sent in the application.

Step 2 is where the user actually creates a profile for the organization.

If we think step 1 as applying and step 2 as creating a profile, it feels less duplicative. If you agree, please feel free to change the language as appropriate. And if Kathy and Elmer agree, I'll close this ticket.

**Comment by kngfrank** [comment]
Closing. Not an issue.
