### ISSUE TITLE
Only one chance to register or join an org is a problem  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#95]
From: KDaniels@ghla.org<br>
Subject: Only one chance to register or join an org is a problem<br>
Date: March 15, 2016 at 04:45PM<br><br>
If someone uses the Validation Link once but doesn&rsquo;t register their org or become an editor, they don&rsquo;t get to use it again and therefore cannot register or associate with an organization.&nbsp; And once they have logged in there doesn&rsquo;t appear to be any way for them to then associate with an organization or select to be an editor.&nbsp; We should give them those 2 choices when they log in if not already with an organization. &nbsp; There is a problem with trying to be an editor.&nbsp; Will put that in another email. &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
KGF to test, clarify, fix if possible, and close or assign.

**Comment by kngfrank** [comment]
I've added links to the site so people can subscribe to a group or register their organization. Open a new ticket if you don't like how things are set up.
