### ISSUE TITLE
cannot request group membership  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#96]
From: KDaniels@ghla.org<br>
Subject: cannot request group membership<br>
Date: March 15, 2016 at 04:52PM<br><br>
I use the validation link and select to be an Editor.&nbsp; The list of Orgs comes up.&nbsp; When I select to Request Group Membership for an Org, I get a message that I am not logged in and the login screen comes up.&nbsp; When I attempt to log in with either the email address or the user name that I just created, it tells me that it&rsquo;s an unrecognized user name or password.&nbsp; &nbsp; As the Org Admin, I do not get an email that they have requested to be an Editor. &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
This needs to be tested on production site.

**Comment by kngfrank** [comment]
Can't replicate on dev. Closing.
