### ISSUE TITLE
File Browser for OrgAdmin  via KDaniels@ghla.org

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#99]
From: KDaniels@ghla.org<br>
Subject: File Browser for OrgAdmin<br>
Date: March 17, 2016 at 10:31AM<br><br>
Org Admin logs in and under My Profile &ndash; has a tab for &ldquo;File Browser&rdquo;.&nbsp; Unable to upload files and not showing files that OrgAdmin had uploaded for Classes. &nbsp; &nbsp;<br><br>
via Gmail

**Comment by kngfrank** [comment]
I think this is a problem only when people connect from within Citrix in our network. Works outside Citrix in Firefox and IE. Closing.
